### ISSUE TITLE
CLI fails with Node 22 in latest Docker image (yargs.usage is not a function)

### ISSUE THREAD

**Issue by Stellaway** [nanawel/our-shopping-list#46]
Hi,

I tried to run the CLI as described in the README for my singleboard preference:

`docker compose exec app node cli.js board:create --singleboard`

but it fails with the following error:

```
/app/cli.js:16
  .usage('$0 <cmd> [args]')
   ^

TypeError: yargs.usage is not a function
    at Object.<anonymous> (/app/cli.js:16:4)
    ...
Node.js v22.18.0
```

I noticed that the current :latest Docker image seems to use Node.js v22.18.0.
With this version, the CLI doesn’t seem to work.

I tried using version 3.5.5, and it works with in that version, it uses v20.19.2

**Comment by nanawel** [comment]
Hi @Stellaway 

You're right, I didn't check if the CLI was still working after the latest big refactoring and upgrade to Node 22.

I'll take a look.

**Comment by nanawel** [comment]
OK, `yargs` made some changes in the API and I didn't read the changelog 🤦‍♂️ 

The fix is ready and pushed to the master branch. I'll release the Docker image in a few days but if you want to try you can build it yourself.

In the meantime, there's no drawbacks sticking to 3.x because 4.x brings almost no feature improvements, only refactorings and upgrades of the core. And you'll be able to upgrade to 4.x without risk when it's ready.

**Comment by nanawel** [comment]
Fixed in https://github.com/nanawel/our-shopping-list/releases/tag/4.0.2
